### ISSUE TITLE
br en trop dans le widget

### ISSUE THREAD

**Issue by llaumgui** [d9-197/blink_camera#10]
Pour moi sur le widget "Prendre une vidéo", il y a un <br> en trop. En effet, si on le veut il faut passer par la case à cocher "retour à la ligne forcé". Du coup le <br> ne sert à rien et on ne peut pas le retirer.

**Comment by d9-197** [comment]
Hello
Pas de br ici. -> Affichage standard.
Je pense que c'est la longueur du nom de la commande qui fait cela.
Duke

**Comment by llaumgui** [comment]
J'ai ça moi:
```
<span class="cmd reportModeHidden cmd-widget" style="display: inline !important;margin-right: 2px;" data-type="action" data-subtype="other" data-cmd_id="6500" data-cmd_uid="cmd6500__1161545205__" data-version="dashboard" data-eqlogic_id="523"><br>
  <a class="btn btn-sm btn-default action cmdName tooltips" title="Prendre une vidéo" style="background-color:#9575cd !important;border-color : transparent !important;margin-top: 2px;"><i class="fa fa-video-camera"></i></a>
  <script>
    $('.cmd[data-cmd_uid=cmd6500__1161545205__]:last .action').off('click').on('click', function () {
      jeedom.cmd.execute({id: '6500'});
    });
    if ($('.cmd[data-cmd_uid=cmd6500__1161545205__]:last').prev().data('subtype') != undefined && $('.cmd[data-cmd_id=6500]:last').prev().data('subtype') != 'other'
    && $('.cmd[data-cmd_uid=cmd6500__1161545205__]:last').prev().css('display') != 'block') {
      $('.cmd[data-cmd_uid=cmd6500__1161545205__]:last').prepend('<br/>');
    }
  </script>
</span>
```
Après il y a un prepend qui rajoute un <br /> mais moi j'ai un <br>.

**Comment by llaumgui** [comment]
Hum la cache à cocher rajoute un <br /> : https://github.com/d9-197/blink_camera/blob/e9b60d979ad73027319e3d05f8083fea6e009c17/core/class/blink_camera.class.php#L1202

**Comment by llaumgui** [comment]
Ok, c'est le JS qui rajoute le <br> je viens de changer la position et plus de problème.

**Comment by d9-197** [comment]
Quel JS ? celui du plugin ?
J'ai une correction à faire ou je peux fermer l'issue ?

Es tu sur le widget standard ?
