### ISSUE TITLE
Erreurs du jour

### ISSUE THREAD

**Issue by Sebkre** [d9-197/blink_camera#11]
Erreurs du jour :
![Cron](https://user-images.githubusercontent.com/53336772/62291286-d92edd80-b463-11e9-93d6-2da21c6453fa.PNG)

**Comment by d9-197** [comment]
Bonjour
tu es sur la dernière version du plugin ?
Je pense que la dernière version a résolu les erreurs "cron"
Pour l'erreur sur le delete, je vais regarder.

**Comment by Sebkre** [comment]
Celle du 31/07 à 8h55.
