### ISSUE TITLE
Listes déroulantes vides lors de création d'une camera

### ISSUE THREAD

**Issue by Rm1TR** [d9-197/blink_camera#12]
**Describe the bug**
Les menus "réseau" et "camera" apparaissent vides lors de la création d'une camera dans l'onglet équipement  avec une icone "sens interdit" au survol de la souris.
Pourtant les credentials sont corrects (revalidés) et bien sauvegardés dans la configuration du plugin. J'ai tenté avec un mauvais mot de passe, j'ai eu une erreur différente dans les logs ; donc pour moi cela ne vient pas d'une erreur de compte Blink

**Expected behavior**
les listes devraient montrer le réseau + camera

**Desktop (please complete the following information):**
 - OS: windows
 - Browser Chrome
 - Version [76.0.3809.100]

**Plugin**
Version bêta 
installée ce jour depuis Github

**Comment by d9-197** [comment]
Pouvez vous retester avec la version que je viens de faire (branche stable) ?

**Comment by Rm1TR** [comment]
Testé à nouveau avec version aeb2193a5be6c5c668cb7c8205393c798aaa82d6 branche stable. Jeedom 3.3.29. Erreur toujours présente

Dans les log "info" je pense avoir vu une erreur de typo, mais je doute que ce soit la cause du bug. Au cas où : "create new action : arm_netrwork". je pense qu'il y a un "r" en trop dans netRwork. Idem pour l'action disarm

**Comment by d9-197** [comment]
Ok
Je n'arrive pas à reproduire l'erreur.
Sans me donner votre mot de passe, avez vous des caractères spéciaux dans votre mdp ?

**Comment by Rm1TR** [comment]
Non je n'ai pas de caractère spécial. Par contre j'ai un espace dans le nom de mes cameras/
J'ai tenté en mettant un mauvais mdp j'ai bien l'erreur "Impossible de se connecter au compte Blink. Vérifiez vos indentifiants et mot de passe. Recharger la page ensuite (F5)." que je n'ai pas avec le bon mdp.
J'ai essayé sous IE. Même comportement.
Ou alors il y a une manip à faire coté Blink pour accepter les requetes API ?

**Comment by d9-197** [comment]
Bonjour

Certains ont la même erreur que toi.
Ils ont contourné le pb en ajoutant au moins une vidéo a la caméra.
En rechargeant la page ensuite.

Si ca marche aussi chez toi, la correction sera faite en septembre
Duke

**Comment by Rm1TR** [comment]
Effectivement. Avec une vidéo enregistrée, les menus se sont débloqués.
Merci

**Comment by d9-197** [comment]
Corrigée dans prochaine version
