### ISSUE TITLE
url vignette

### ISSUE THREAD

**Issue by jean2979** [d9-197/blink_camera#14]
salut,j'aimerai récupérer l'url de la vignette pour me l'envoyer par email ou telegram, actuellement on a le chemin mais pas l'url complète (il manque https.............), merci :)

**Comment by d9-197** [comment]
Excellent idée !
Ce sera dans la version de ce soir.
Il te faudra peut être recréer l'équipement de la caméra (essayes dans un premier temps de juste faire "sauvegarder" depuis la page de configuration de l'équipement).
Si tu pouvais tester ca et me faire tes retours.
Alain

**Comment by jean2979** [comment]
Salut Alain,Et merci pour ta réponse. Peut être qu'il y a plus simple que par l'url, mais je t'envoies un screen de ce que j'ai obtenu en m'envoyant un message en ajoutant mon adresse + le chemin de ton plugin sur telegram. Suis pas super doué mais ça me paraît sympa comme fonction.Peut-être qu'on peut envoyer l'image directement et/ou sans que le lien s'affiche, mais c'est une piste.À bientôt. Le 1 févr. 2020 19:16, d9-197 <notifications@github.com> a écrit :Excellent idée !

Ce sera dans la version de ce soir.

Il te faudra peut être recréer l'équipement de la caméra (essayes dans un premier temps de juste faire "sauvegarder" depuis la page de configuration de l'équipement).

Si tu pouvais tester ca et me faire tes retours.

Alain

**Comment by jean2979** [comment]
J'ai testé beta et stable,pas vu de changement,j'ai loupé un truc ? merci

**Comment by d9-197** [comment]
La mise à jour n'est peut être pas déployée sur le market.
Alain

**Comment by jean2979** [comment]
Tu l'as appliqué sur la version stable ?
Merci :)

**Comment by d9-197** [comment]
Oui uniquement sur la stable.
J'ai du louper quelque chose...
Je peux pas regarder aujourd'hui.
Peut-être ce soir...

**Comment by d9-197** [comment]
Bon finalement j'ai trouvé 5 minutes.
La mise à jour est passée.
Tu vas pouvoir tester

**Comment by jean2979** [comment]
rien de mon côté pour le moment,je te tiens au courant ;)

**Comment by jean2979** [comment]
j'ai réussi en installant directement le fichier depuis github, pour la vidéo, j'ai bien le lien valide de la dernière vidéo (last.mp4). Par contre pour la vignette, le lien se termine par "thumbmail", et si je copie colle ce lien dans mon navigateur par exemple, je n'ai pas accès à la vignette

**Comment by jean2979** [comment]
je crois que j'ai trouvé, ça vient du https et http.
mais le thumbnail donne pas la vignette de la dernière vidéo mais celle de la vignette de la caméra.

**Comment by d9-197** [comment]
Ok... Il manque .jpg
Je regarderai

**Comment by jean2979** [comment]
Le .jpg y est, mais ça donne pas la vignette de la dernière vidéo, ça donne la vignette de la caméra (celle qu'on a sur la page d'accueil de l'appli).
Et le lien en http n'affiche pas la vignette car il manque le "s". (Ça dépend si l'on est en https surement).
Ça marche nickel pour la vidéo, même s'il manque le "s" aussi.
On a un aperçu de la vidéo directement dans telegram, c'est top, merci pour cette MAJ.

**Comment by jean2979** [comment]
je reviens vers toi,en fait l'adresse,on a qu'à changer nous même, le truc nickel c'est que si on veut le lien de la dernière vidéo on met "last" dans le lien et on a notre vidéo.
Ce serait la même chose avec la photo ?
last.mp4 et last.jpg dans le dossier médias ?
merci

**Comment by d9-197** [comment]
Je ne génère pas le "last.jpg"
Je l'ajouterai dans la prochaine version.
Alain

**Comment by jean2979** [comment]
c'est bizarre ce last, je fais tests sur tests mais le last en question c'est toujours la même vidéo depuis ce matin... :/
alors que j'en ai fait d'autres depuis.

EDIT : je crois qu'il faut rafraîchir avant.

c'est vrai qu'un lien bateau avec last.mp4 ou last.jpg c'était parfait.
Une fois que tu connais le lien,c'est très facile à utiliser

pour l'url des fois elle est incomplète, à la place de mon adresse jeedom,j'ai un troisième "/".
ça donne ça : http:///plugins/blink_camera/medias/390/thumbnail.jpg

tu penses pouvoir générer une dernière vidéo et/ou une dernière photo en leur donnant le nom "last" ? et peut être faire un refresh auto du coup ?

**Comment by jean2979** [comment]
Bon,galère, je sais pas si c'est bon plan le même nom pour toutes les notifs (last) 
telegram me sort tjs la même vidéo alors que si je mets le lien dans mon navigateur ça fonctionne, c'est ma dernière vidéo qui sort et pas celle de ce matin qui ne cesse de sortir sur telegram.

désolé de t'ennuyer

**Comment by jean2979** [comment]
Salut, peut-être une piste ici ?

https://forum.jeedom.com/viewtopic.php?t=42549

**Comment by jean2979** [comment]
J'ai trouvé 😍
J'ai échangé l'espace entre date et heure par un tiret.
Ainsi le chemin de la vidéo ou de la photo peut s'ajouter directement au lien de notre site. (Avec l'espace entre les 2 on obtenait pas un lien valide)
Donc on peut faire un scénario envoi message telegram composé comme suit :
https://monjeedom.com#[CAMERAS][VOITURE][Chemin vidéo]#
Et ça te donne bien la dernière prise.
La vidéo est lue directement sur telegram, plus besoin de l'appli blink limite.

Peut-être pourrais tu échanger l'espace entre date et heure dans le plugin dans une prochaine mise à jour ? (Je l'ai fait via jeexplorer directement depuis mon jeedom)

Merci pour tout, à bientôt

**Comment by jean2979** [comment]
L'inconvénient avec cette méthode c'est qu'on ne peut utiliser la balise <a href="</a>
Pour modifier l'affichage de l'url 
Là on a l'url complète + la photo ou la vidéo

Le lien que tu as ajouté lors de la dernière maj affiche toujours http:///puis chemin, je sais pas pourquoi, mais du coup le lien est invalide

**Comment by d9-197** [comment]
Une correction a été livrée dans la version du 26/02.

**Comment by jean2979** [comment]
Merci pour tout Alain
