### ISSUE TITLE
Problemes depuis la derniere version du 29-02-2020

### ISSUE THREAD

**Issue by maxnumberone** [d9-197/blink_camera#15]
Hello,
Depuis la dernière mise a jour du plugin j'ai pas mal de soucis.
J'ai supprimé et réinstallé le plugin mais j'ai toujours les même problèmes.
Déjà j'ai très régulièrement le message ci dessous dans jeedom :

La tache plugin::cron n'arrive pas à finir à cause du plugin : blink_camera nous vous conseillons de désactiver le plugin et de contacter l'auteur

Sauf que je ne peux pas désactiver le plugin car la roue crantée tourne dans le vide (idem quand je cherche a enregistrer mes commandes (mes équipements/commandes/sauvegarder), ca ne rend jamais la main.
Si je le désinstalle je n'ai plus de souci particulier (si ce n'est qu'il n'est plus installé :) ).

Dans les logs du plugin j'ai ces messages (le premier je l'ai un très très grand nombre de fois): 

[2020-03-02 22:50:49][ERROR] : Erreur exécution de la commande [Terrain][Blink Terasse][Rafraichir] : sink must not be a boolean
[2020-03-02 22:50:49][ERROR] : Erreur sur la fonction cronHourly du plugin : sink must not be a boolean

A savoir qu'il récupère bien certaines infos mais pas toutes, en KO il y a par ex la puissance du signal wifi et le les retours système/camera armé.
Vidéo, piles, température semblent eux OK.

Merci pour votre aide

**Comment by d9-197** [comment]
Bonjour,
Vous êtes sur quelle version de Jeedom ? et sur quel système (DIY ? RPI? )
Cordialement,
Alain

**Comment by Iols974** [comment]
Bonjour,

Y a t-il un moyen de résoudre ce problème ? 

On en discute  sur le forum de jeedom : https://community.jeedom.com/t/changement-de-service-fin-du-plugin-blink-camera/27204/5

merci

**Comment by d9-197** [comment]
Bonjour
J'ai ajouté un commentaire sur le forum (pour résumer : pas de solution dans l'immédiat)

**Comment by Iols974** [comment]
> Bonjour
> J'ai ajouté un commentaire sur le forum (pour résumer : pas de solution dans l'immédiat)

bonjour merci !

**Comment by d9-197** [comment]
problème corrigé en 2.0.0
