### ISSUE TITLE
Gestion de l'affichage et de la disposition

### ISSUE THREAD

**Issue by llaumgui** [d9-197/blink_camera#4]
Actuellement la configuration avancée d'un équipement ne propose pas ses 2 onglets :

- Affichage.
- Disposition.

Ceci permettrait de personnaliser grandement le widget.

**Comment by d9-197** [comment]
J'ai ajouté une option pour utiliser le widget **mais** :
La vignette n'est alors pas affichée.
J'ai également ajouté des options de configurations sur les actions pour pouvoir configurer des On/Off.
**Par contre :**
Je ne sais plus comment on configure proprement un On/Off
@llaumgui : si tu peux m'aider sur le On/off (me dire ce qu'il manque pour toi dans la config)

**Comment by llaumgui** [comment]
Bonjour,

je comprend pas quelques chose. Un équipement se compose de commande. Et une commande à un widget.
Pour moi il faut que tout soit commande. Tu mets la vignette et dessous toutes les commandes. Après pour gérer du on/off, les gens se débrouille avec les widgets.

Sinon, j'ai bien accès à disposition, mais lorsque je demande d'afficher 'équipement ça ne marche pas.

**Comment by d9-197** [comment]
Bonjour
Oui je vais créer une commande pour la vignette.
En fait je suis parti de l'exemple du plugin Caméra. 
Il gère tout avec un widget custom.
Après, la configuration des commandes est elle aussi particulière. Je vais voir pour rétablir avec une configuration standard de l'onglet Commandes.

Je pense que mon choix de partir du plugin Caméra était une erreur avec un peu de recul...

**Comment by llaumgui** [comment]
En fait je viens de regarder et le plugin Caméra n'a pas de commande pour la vignette... Je pense que c'est du fait qu'il n'y a pas de widget pour le gérer. Après tout le reste est en commande.

Donc idéalement une case à cocher pour afficher ou non la vignette et les reste en commande dessous.

**Comment by d9-197** [comment]
Bonjour
A tester dans la nouvelle version.
(Sur la branche beta)
