### ISSUE TITLE
Afficher ou pas les éléments de la tuile

### ISSUE THREAD

**Issue by llaumgui** [d9-197/blink_camera#5]
**Describe the bug**
Lorsque je décoche afficher pour la température, cette dernière est toujours affichée sur la tuile

**To Reproduce**
Aller dans la configuration d'un équipement
1. Décocher "Afficher" pour la température
2. Sauvegarder

**Expected behavior**
La température ne doit plus s'afficher.

**Comment by d9-197** [comment]
@llaumgui 
Je n'arrive pas à reproduire chez moi.
Peut être que cela a été corrigé par mes dernières modifications ?
Peux tu retester avec la dernière version ?

**Comment by d9-197** [comment]
Erreur similaire signalée sur le Forum. A investiguer...

**Comment by Sebkre** [comment]
Bonjour,

En fait je pense que j'ai donné la réponse sur le forum.

Pour afficher / masquer des éléments il faut le faire au niveau du plugin :
Chemin : Plugins / Sécurité / Blink Camera
Aller sur la caméra concernée puis dans l'onglet "commandes"
Cocher / décocher les éléments voulus
