### ISSUE TITLE
Armer/Deasrmer caméra par caméra 

### ISSUE THREAD

**Issue by dudulos** [d9-197/blink_camera#9]
Peut-être utile, un armement/désarmement caméra par caméra.
Peut-être en utilisant la détection de mouvement caméra par caméra ?

**Comment by d9-197** [comment]
La détection de fait bien indépendamment pour chaque caméra.
J'ajouterai l'armement par caméra.

**Comment by d9-197** [comment]
Intégré dans prochaine version (ce soir)
